"""
Django settings for TeamConnect project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$-+^e3$ki*3t)#@dm5959&4n=&+%e*qnckq0qwu!((cx&w%cue'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',
    'channels'
]

AUTH_USER_MODEL = 'chat.CustomUser'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TeamConnect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'chat' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TeamConnect.wsgi.application'
ASGI_APPLICATION = 'TeamConnect.asgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'

# where collectstatic will gather files
STATIC_ROOT = BASE_DIR / "staticfiles"

# your local development static files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' 

# Enable email backend
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'# Uses SMTP backend for sending emails
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 587# Port number (587 = TLS)
EMAIL_USE_TLS = True# Enables secure connection
EMAIL_HOST_USER = 'swethadomatoti@gmail.com'# Sender email address
EMAIL_HOST_PASSWORD = 'vikejxmcrmctqkaq'# Email password / App password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER # Default sender email
 

CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://red-d5gb2bngi27c73blqhk0:6379')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://red-d5gb2bngi27c73blqhk0:6379')
 

REDIS_URL=os.environ.get('REDIS_URL', 'redis://red-d5gb2bngi27c73blqhk0:6379')
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer',
#         'CONFIG': {
#             'hosts': [('127.0.0.1', 6379)],            
#         },
#     },
# }
import os
import dj_database_url

SECRET_KEY = os.environ.get("SECRET_KEY", "fallback-secret")
DEBUG = os.environ.get("DEBUG", "False") == "True"
ALLOWED_HOSTS = ["teamconnect-1-wn7t.onrender.com", "localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = ["https://teamconnect-1-wn7t.onrender.com"]

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # add this
    *MIDDLEWARE,
]

# Database
DATABASE_URL='postgresql://teamconnect_ugn2_user:NP0tQdWVz9kct1JnUbn8LTSHFoaGnVv9@dpg-d62opishg0os73ep6r0g-a/teamconnect_ugn2'
# DATABASES = {
#     'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'))
# }
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),  # uses DATABASE_URL environment variable from Render
        conn_max_age=600,                        # keeps connections alive
        ssl_require=True                          # important for Render Postgres
    )
}

 


# Redis (optional)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL","redis://red-d5gb2bngi27c73blqhk0:6379"),
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/room/'
LOGOUT_REDIRECT_URL = '/login/'